name: "Check Pull Request"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Dump steps context
        run: |
          echo '${{ toJSON(github.event.pull_request) }}'
          echo '${{ github.event.pull_request}}'
      - name: PR Title Verify
        uses: satvik-s/pr-title-check@1.1.0
        with:
          pattern: '^(fix|feat|chore|doc|style|refactor|perf|revert|test)(\(\w\))?: .*$'
      - name: Check Body
        id: check-body
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '^.*(TEST).*$'
      - name: Comment
        if: ${{ steps.check-body.outputs.match == '' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            This is a test ! :wave:
